#!/usr/bin/env bash

IMAGE_NAME="openwrt-builder"

if [ -z "$(docker images -q $IMAGE_NAME 2>/dev/null)" ]; then
    echo "image $IMAGE_NAME doesn't exist, start build..."
    docker build . -t openwrt-builder
fi

docker run -v ./:/workspace -u "$(id -u)":"$(id -g)" -it openwrt-builder bash
